trigger:
- '*'
stages:
# -------------------------------
# Stage 4: Build Python Function App
# -------------------------------
- stage: Package_FunctionApp
  displayName: "Package Python Function App"
  jobs:
  - job: Package_FunctionApp
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: UsePythonVersion@0
      displayName: "Set Python Version"
      inputs:
        versionSpec: '3.11.9'
        addToPath: true

    - script: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
      workingDirectory: 'LaekningGenAIRecommendationModule'
      displayName: "Install Python Dependencies"

    - task: ArchiveFiles@2
      displayName: "Package Function App"
      inputs:
        rootFolderOrFile: 'LaekningGenAIRecommendationModule'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish Function App Package"
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        artifactName: 'drop-functionapp'




