trigger:
  branches:
    include:
    - '*'
    
    
stages:
- stage: Validate_FunctionApp
  displayName: "Validate Python Function App"
  jobs:
  - job: Validate_FunctionApp
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      displayName: "Set Python Version"
      inputs:
        versionSpec: '3.11'
        addToPath: true
    - task: CmdLine@2
      displayName: "Validate requirements.txt"
      inputs:
        script: |
          pip install -r requirements.txt
        workingDirectory: 'LaekningGenAIRecommendationModule'
        
        
- stage: Package_FunctionApp
  displayName: "Package Python Function App"
  dependsOn:
  - Validate_FunctionApp
  jobs:
  - job: Package
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PublishBuildArtifacts@1
      displayName: "Publish Function App Source"
      inputs:
        pathToPublish: 'LaekningGenAIRecommendationModule'
        artifactName: 'functionapp-src'
        
        
- stage: Deploy_FunctionApp
  displayName: "Deploy Python Function App"
  dependsOn:
  - Package_FunctionApp
  jobs:
  - deployment: Deploy_FunctionApp
    pool:
      vmImage: ubuntu-latest
    environment:
      name: spike
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - task: 30f35852-3f7e-4c0c-9a88-e127b4f97211@1
            inputs:
              alias: current
              artifact: functionapp-src
          - task: AzureFunctionApp@2
            displayName: 'Azure Function Deploy: Gen AI Module'
            inputs:
              azureSubscription: 'Laekning Service Connection'
              appType: functionAppLinux
              appName: '$(GenAIAppName)'
              runtimeStack: PYTHON|3.11
              package: '$(Pipeline.Workspace)/functionapp-src'
          - task: AzureCLI@2
            displayName: 'Install Azure Functions Extension'
            inputs:
              azureSubscription: 'Laekning Service Connection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az extension add -n functionapp
          - task: AzureCLI@2
            displayName: 'Sync Azure Functions Triggers'
            inputs:
              azureSubscription: 'Laekning Service Connection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp sync-functions --name $(GenAIAppName) --resource-group LaekningTestResourceGroup
