trigger:
- '*'

variables:
  - group: Release
  
stages:



# -------------------------------
# Stage 3: Build ASP.NET Core App
# -------------------------------
- stage: Build_ASPNET
  displayName: "Build ASP.NET Core App"
  #dependsOn: Deploy_FunctionApp
  jobs:
  - job: Build_ASPNET
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 8.x'
      inputs:
        packageType: sdk
        version: '8.x'
    
    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: Laekning/wwwroot

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: 'Laekning/Laekning.csproj'
        arguments: '--prerelease'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - Release'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration Release'
        projects: 'Laekning/Laekning.csproj'

# -------------------------------
# Stage 4: Run Unit Tests
# -------------------------------
- stage: Test_ASPNET
  variables:
    buildConfiguration: 'Release'
  displayName: "Run ASP.NET Unit Tests"
  dependsOn: Build_ASPNET
  jobs:
  - job: Test_ASPNET
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 8.x'
      inputs:
        packageType: sdk
        version: '8.x'
        
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: 'Laekning.Tests.csproj' 
        
        
