trigger:
- '*'
stages:
# -------------------------------
# Stage 4: Build C++ EventHub Project
# -------------------------------
- stage: Build_EventHub
  variables:
    buildConfiguration: 'Release'
  displayName: "Build C++ EventHub"
  jobs:
  - job: Build_EventHub
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: CMake@1
      displayName: Configure
      inputs:
        workingDirectory: 'LaekningEventHub'
        cmakeArgs: '-B build -S . -G "Visual Studio 17 2022" -A x64'

    - task: CMake@1
      displayName: Build
      inputs:
        workingDirectory: 'LaekningEventHub'
        cmakeArgs: '--build build --config Release'

    - task: PublishBuildArtifacts@1
      displayName: Publish Executable
      inputs:
        PathtoPublish: 'build/Release'
        ArtifactName: 'drop'
        publishLocation: 'Container'



