trigger:
- '*'

stages:
# -------------------------------
# Stage 1: Validate Python Function App
# -------------------------------
- stage: Validate_FunctionApp
  displayName: "Validate Python Function App"
  jobs:
  - job: Validate_FunctionApp
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      displayName: "Set Python Version"
      inputs:
        versionSpec: '3.11'
        addToPath: true

    - script: |
        pip install -r requirements.txt
      workingDirectory: 'LaekningGenAIRecommendationModule'
      displayName: "Validate requirements.txt"

# -------------------------------
# Stage 2: Package & Publish Artifact
# -------------------------------
- stage: Package_FunctionApp
  displayName: "Package Python Function App"
  dependsOn: Validate_FunctionApp
  jobs:
  - job: Package
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PublishBuildArtifacts@1
      displayName: "Publish Function App Source"
      inputs:
        pathToPublish: 'LaekningGenAIRecommendationModule'
        artifactName: 'functionapp-src'

# -------------------------------
# Stage 3: Deploy Python Function App
# -------------------------------
- stage: Deploy_FunctionApp
  displayName: "Deploy Python Function App"
  dependsOn: Package_FunctionApp
  jobs:
  - deployment: Deploy_FunctionApp
    pool:
      vmImage: ubuntu-latest
    environment: 
      name: spike
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          # Download artifact
          - download: current
            artifact: functionapp-src

          # Deploy using AzureFunctionApp@2, let Oryx handle build
          - task: AzureFunctionApp@2
            displayName: 'Azure Function Deploy: Gen AI Module'
            inputs:
              azureSubscription: 'Laekning Service Connection'
              appType: functionAppLinux
              appName: '$(GenAIAppName)'
              runtimeStack: PYTHON|3.11
              package: '$(Pipeline.Workspace)/functionapp-src'

          # Sync triggers to ensure functions are registered
          - task: AzureCLI@2
            displayName: 'Sync Azure Functions Triggers'
            inputs:
              azureSubscription: 'Laekning Service Connection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp sync-functions --name $(GenAIAppName) --resource-group LaekningTestResourceGroup
